//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENK.LycaAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LycaAPI.LycaAPISoap")]
    public interface LycaAPISoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ENK.LycaAPI.HelloWorldResponse HelloWorld(ENK.LycaAPI.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ENK.LycaAPI.HelloWorldResponse> HelloWorldAsync(ENK.LycaAPI.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name URL from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LycaAPIRequest", ReplyAction="*")]
        ENK.LycaAPI.LycaAPIRequestResponse LycaAPIRequest(ENK.LycaAPI.LycaAPIRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LycaAPIRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<ENK.LycaAPI.LycaAPIRequestResponse> LycaAPIRequestAsync(ENK.LycaAPI.LycaAPIRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ENK.LycaAPI.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ENK.LycaAPI.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ENK.LycaAPI.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ENK.LycaAPI.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LycaAPIRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LycaAPIRequest", Namespace="http://tempuri.org/", Order=0)]
        public ENK.LycaAPI.LycaAPIRequestRequestBody Body;
        
        public LycaAPIRequestRequest() {
        }
        
        public LycaAPIRequestRequest(ENK.LycaAPI.LycaAPIRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LycaAPIRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string URL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SOAPAction;
        
        public LycaAPIRequestRequestBody() {
        }
        
        public LycaAPIRequestRequestBody(string URL, string Data, string SOAPAction) {
            this.URL = URL;
            this.Data = Data;
            this.SOAPAction = SOAPAction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LycaAPIRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LycaAPIRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public ENK.LycaAPI.LycaAPIRequestResponseBody Body;
        
        public LycaAPIRequestResponse() {
        }
        
        public LycaAPIRequestResponse(ENK.LycaAPI.LycaAPIRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LycaAPIRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LycaAPIRequestResult;
        
        public LycaAPIRequestResponseBody() {
        }
        
        public LycaAPIRequestResponseBody(string LycaAPIRequestResult) {
            this.LycaAPIRequestResult = LycaAPIRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LycaAPISoapChannel : ENK.LycaAPI.LycaAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LycaAPISoapClient : System.ServiceModel.ClientBase<ENK.LycaAPI.LycaAPISoap>, ENK.LycaAPI.LycaAPISoap {
        
        public LycaAPISoapClient() {
        }
        
        public LycaAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LycaAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LycaAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LycaAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ENK.LycaAPI.HelloWorldResponse ENK.LycaAPI.LycaAPISoap.HelloWorld(ENK.LycaAPI.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ENK.LycaAPI.HelloWorldRequest inValue = new ENK.LycaAPI.HelloWorldRequest();
            inValue.Body = new ENK.LycaAPI.HelloWorldRequestBody();
            ENK.LycaAPI.HelloWorldResponse retVal = ((ENK.LycaAPI.LycaAPISoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ENK.LycaAPI.HelloWorldResponse> ENK.LycaAPI.LycaAPISoap.HelloWorldAsync(ENK.LycaAPI.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ENK.LycaAPI.HelloWorldResponse> HelloWorldAsync() {
            ENK.LycaAPI.HelloWorldRequest inValue = new ENK.LycaAPI.HelloWorldRequest();
            inValue.Body = new ENK.LycaAPI.HelloWorldRequestBody();
            return ((ENK.LycaAPI.LycaAPISoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ENK.LycaAPI.LycaAPIRequestResponse ENK.LycaAPI.LycaAPISoap.LycaAPIRequest(ENK.LycaAPI.LycaAPIRequestRequest request) {
            return base.Channel.LycaAPIRequest(request);
        }
        
        public string LycaAPIRequest(string URL, string Data, string SOAPAction) {
            ENK.LycaAPI.LycaAPIRequestRequest inValue = new ENK.LycaAPI.LycaAPIRequestRequest();
            inValue.Body = new ENK.LycaAPI.LycaAPIRequestRequestBody();
            inValue.Body.URL = URL;
            inValue.Body.Data = Data;
            inValue.Body.SOAPAction = SOAPAction;
            ENK.LycaAPI.LycaAPIRequestResponse retVal = ((ENK.LycaAPI.LycaAPISoap)(this)).LycaAPIRequest(inValue);
            return retVal.Body.LycaAPIRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ENK.LycaAPI.LycaAPIRequestResponse> ENK.LycaAPI.LycaAPISoap.LycaAPIRequestAsync(ENK.LycaAPI.LycaAPIRequestRequest request) {
            return base.Channel.LycaAPIRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ENK.LycaAPI.LycaAPIRequestResponse> LycaAPIRequestAsync(string URL, string Data, string SOAPAction) {
            ENK.LycaAPI.LycaAPIRequestRequest inValue = new ENK.LycaAPI.LycaAPIRequestRequest();
            inValue.Body = new ENK.LycaAPI.LycaAPIRequestRequestBody();
            inValue.Body.URL = URL;
            inValue.Body.Data = Data;
            inValue.Body.SOAPAction = SOAPAction;
            return ((ENK.LycaAPI.LycaAPISoap)(this)).LycaAPIRequestAsync(inValue);
        }
    }
}
